- name: install Kubeadm cluster
  hosts: all
  become: true
  vars:
    playbook_lock: /home/ubuntu/deployed.txt
    use_cilium: "yes"
    pod_network_cidr: '100.64.0.0/14'
    service_cidr: '100.68.0.0/16'
    cilium_version: '1.17.8'
    cilium_use_encryption: "no"
    # cilium_encryption_type can be ipsec or wireguard
    cilium_encryption_type: wireguard

  tasks:

    - name: Get master IP from terraform output file
      ansible.builtin.include_vars:
        file: master_private_ip.yaml
        name: master
      delegate_to: localhost
      when: inventory_hostname in groups['master']

    - name: Template master node
      ansible.builtin.template:
        src: templates/install_master.sh.j2
        dest: /tmp/install_master.sh
      delegate_to: localhost
      when: inventory_hostname in groups['master']

    - name: execute master node script
      ansible.builtin.script: /tmp/install_master.sh
      args:
        executable: /bin/bash
        creates: "{{ playbook_lock }}"
      when: inventory_hostname in groups['master']

    - name: Install worker nodes
      ansible.builtin.script: scripts/install_worker.sh
      args:
        executable: /bin/bash
        creates: "{{ playbook_lock }}"
      when: inventory_hostname in groups['worker']

    - name: Get token 
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      args:
        creates: "{{ playbook_lock }}"
      when: inventory_hostname in groups['master']
      

    - name: set the fact
      set_fact:
        execute_this: "{{ join_command['stdout'] }}"
      when: inventory_hostname in groups['master']

    - name: print fact
      ansible.builtin.debug:
        var: execute_this
      when: inventory_hostname in groups['master']

    - name: execute command on workers
      ansible.builtin.command: "{{ execute_this }}"
      when: inventory_hostname in groups['master']
      delegate_to: "{{ item }}"
      loop: "{{ groups['worker'] }}"
      args:
        creates: "{{ playbook_lock }}"
    
    - name: Set file
      ansible.builtin.file:
        path: "{{ playbook_lock }}"
        state: touch

    - name: Add cilium chart repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"
      when: inventory_hostname in groups['master'] and use_cilium == "yes"

    - name: Deploy Cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        namespace: kube-system
        values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
      when: inventory_hostname in groups['master'] and use_cilium == "yes"

    - name: show master ip
      ansible.builtin.debug:
        msg: "To connect to the master node: ssh -i .ssh/id_rsa-tf ubuntu@{{ inventory_hostname }}" 
      when: inventory_hostname in groups['master']
